const dotenv = require("dotenv");
dotenv.config();
module.exports = {
  PORT: process.env.PORT,
  DB_HOST: process.env.DB_HOST,
  DB_USERNAME: process.env.DB_USERNAME,
  DB_PASSWORD: process.env.DB_PASSWORD,
  DB_PORT: process.env.DB_PORT,
  DB_NAME: process.env.DB_NAME,
  DIALECT: process.env.DIALECT,
  INIT_DB: process.env.INIT_DB,
  FROM_EMAIL: process.env.FROM_EMAIL,
  MAIL_HOST: process.env.MAIL_HOST,
  MAIL_PORT: process.env.MAIL_PORT,
  MAIL_USER: process.env.MAIL_USER,
  MAIL_PASS: process.env.MAIL_PASS,
  TIME_FORMAT: process.env.TIME_FORMAT,
  MAX_SIZE: process.env.MAX_SIZE,
  LOG_LEVEL: process.env.LOG_LEVEL,
  FILE_NAME: process.env.FILE_NAME,
  FOLDER_NAME: process.env.FOLDER_NAME,
  CATEGORY: process.env.CATEGORY,
  ALGORITHM: process.env.ALGORITHM,
  TOKEN_EXPIRES_TIME: process.env.TOKEN_EXPIRES_TIME,
  BSCT_JSON_RPC_URL: process.env.BSCT_JSON_RPC_URL,
  BSC_JSON_RPC_URL: process.env.BSC_JSON_RPC_URL,
  BSC_CONTRACT_ADDRESS: process.env.BSC_CONTRACT_ADDRESS,
  SHASTA_JSON_RPC_URL: process.env.SHASTA_JSON_RPC_URL,
  MAINNET_JSON_RPC_URL: process.env.MAINNET_JSON_RPC_URL,
  NILE_JSON_RPC_URL: process.env.NILE_JSON_RPC_URL,
  NILE_EVENT_SERVER: process.env.NILE_EVENT_SERVER,
  TRON_CONTRACT_ADDRESS: process.env.TRON_CONTRACT_ADDRESS,
  SOLANA_PROGRAM_ID: process.env.SOLANA_PROGRAM_ID,
  RPCENDPOINT: process.env.RPCENDPOINT,
  CONTRACT_ADDRESS1: process.env.CONTRACT_ADDRESS1,
  PASSCODE_LENGTH: process.env.PASSCODE_LENGTH,
  TOKEN_EXPIRES_IN: process.env.TOKEN_EXPIRES_IN,
  LOGGER_ERROR_PATH: process.env.LOGGER_ERROR_PATH,
  LOGGER_COMBINED_PATH: process.env.LOGGER_COMBINED_PATH,
  TEMPLATES_PATH: process.env.TEMPLATES_PATH,
  DEAL_LINK_PATH: process.env.DEAL_LINK_PATH,
};
